pipelines:
  default:
      - step:
          name: Build and test
          image: node:8.6
          script:
            - npm install
            - npm run build
  branches:
    master:
      - step:
          name: Build and Test
          image: node:8.6
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Release
          deployment: production
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync --delete dist s3://$BUCKET_NAME
            # - sh notify.sh $HOOK
